### ISSUE TITLE
deleteTorrent returns HTTP 400

### ISSUE THREAD

**Issue by m4tta** [flowbe/node-qbittorrent-api-v2#7]
Not much else to say... All other methods function as expected. Which is odd because according to the docs all scenarios should return HTTP 200 https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#delete-torrents

I've tried to debug it as much as I can but the request looks proper. It's hitting the correct API endpoint and passes the cookies along.

**Comment by crisdias** [comment]
Are you passing an array of hashes as parameter to deleteTorrent? (as I did)

You should actually use a `|` separated list of arrays, as shown by the link you posted. Thanks you for that, I was stuck here as well.

**Comment by m4tta** [comment]
I ended up forking the repo and fixing the deleteTorrents call. It was missing the `deleteFiles` parameter from the docs linked.

https://github.com/m4tta/node-qbittorrent-api-v2/commit/a00f418a6eda9db7dcb56ab48022cb3d68dc9feb

**Comment by flowbe** [comment]
Closing this issue as it should be fixed by #8. Thanks again to @m4tta for the contribution!
